version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - aws ecr get-login --region us-east-1 --no-include-email
    - REPOSITORY_URI=https://github.com/tanishq111/codepipeline1.git
    - IMAGE_TAG=latest
  build:
    commands:
    - echo Build started on `date`
    - mvn test
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
#artifacts:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
